version: "3.8"

services:
  corona-frontend:
    build: .
    image: "corona-frontend:0.1"
    container_name: "corona_frontend"
    ports:
    - "5000:5000"
    environment:
      - "COVID19_APIKEY=${COVID19_APIKEY}"
      - "FLASK_APP=frontend.py"
