version: "3.0"

services:
  theservice:
    image: theservice:1.0.0
    container_name: test123
    build: .
    ports:
    - "10000:5000"
    environment:
      - "COVID19_APIKEY=${COVID19_APIKEY}"
      - "FLASK_APP=frontend.py"